|
                    concurrent = ${GitlabMaxConcurrentBuilds}
                    check_interval = ${GitlabCheckInterval}
                    [[runners]]
                      name = "${AWS::StackName}"
                      url = "${GitlabUrl}"
                      token = "${GitlabToken}"
                      executor = "docker+machine"
                      environment = [
                        "DOCKER_DRIVER=overlay2",
                        "DOCKER_TLS_CERTDIR=/certs"
                      ]
                      [runners.docker]
                        tls_verify = false
                        image = "${GitlabDockerImage}"
                        privileged = true
                        disable_cache = false
                        volumes = ["/certs/client", "/cache"]
                        shm_size = 0
                      [runners.cache]
                        Type = "s3"
                        Shared = true
                      [runners.cache.s3]
                        ServerAddress = "s3.${AWS::URLSuffix}"
                        BucketName = "${CacheBucket}"
                        BucketLocation = "${AWS::Region}"
                      [runners.machine]
                        IdleCount = ${GitlabIdleCount}
                        IdleTime = ${GitlabIdleTime}
                        MaxBuilds = ${GitlabMaxBuilds}
                        MachineDriver = "amazonec2"
                        MachineName = "gitlab-docker-machine-%s"
                        MachineOptions = [
                          "amazonec2-instance-type=${GitlabRunnerInstanceType}",
                          "amazonec2-region=${AWS::Region}",
                          "amazonec2-vpc-id=${VpcId}",
                          "amazonec2-zone=${AvailabilityZone}",
                          "amazonec2-subnet-id=${SubnetId}",
                          "amazonec2-security-group=${AWS::StackName}-RunnersSecurityGroup",
                          "amazonec2-use-private-address=true",
                          "amazonec2-iam-instance-profile=${RunnersInstanceProfile}"
                          ${LocalSpotVar}
                        ]
                        OffPeakTimezone = "${GitlabOffPeakTimezone}"
                        OffPeakPeriods = ["* * 0-8,18-23 * * mon-fri *", "* * * * * sat,sun *"]
                        OffPeakIdleCount = ${GitlabOffPeakIdleCount}
                        OffPeakIdleTime = ${GitlabOffPeakIdleTime}